// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5qFeEnNObNFo7PpfZBxOjbd9QQlKIkWE',
    appId: '1:868242733842:web:f4baf8c808beac1c3bd1cb',
    messagingSenderId: '868242733842',
    projectId: 'glamor-c90e6',
    authDomain: 'glamor-c90e6.firebaseapp.com',
    storageBucket: 'glamor-c90e6.appspot.com',
    measurementId: 'G-T95MBYL8J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8DNAMo7JR_IIHcUriQn-ncGCfIP4QC3Q',
    appId: '1:868242733842:android:ff7c7e5b4262283b3bd1cb',
    messagingSenderId: '868242733842',
    projectId: 'glamor-c90e6',
    storageBucket: 'glamor-c90e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0EtBBr93JmwoxGZvOkktGywlDKaY06oY',
    appId: '1:868242733842:ios:285e4583a63ed56b3bd1cb',
    messagingSenderId: '868242733842',
    projectId: 'glamor-c90e6',
    storageBucket: 'glamor-c90e6.appspot.com',
    iosClientId: '868242733842-cb0gckhgr47b2rvofm3djpaft4pkgcau.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.gelamor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0EtBBr93JmwoxGZvOkktGywlDKaY06oY',
    appId: '1:868242733842:ios:285e4583a63ed56b3bd1cb',
    messagingSenderId: '868242733842',
    projectId: 'glamor-c90e6',
    storageBucket: 'glamor-c90e6.appspot.com',
    iosClientId: '868242733842-cb0gckhgr47b2rvofm3djpaft4pkgcau.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.gelamor',
  );
}
